plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/frosty/Dev/godot/v4.6/Kingdom-Crumble"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"